repos:
- repo: local
  hooks:
    - id: pycodestyle
      name: PEP8 check
      entry: python -m pycodestyle
      language: system
      files: ^.*\.py$
      args: [--max-line-length=79, --exclude=.venv]